spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:http://localhost:8888'

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"  # Permite el origen de tu frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

security:
  jwt:
    privateKey: 4a0d045593e609435c401089d91421cca7ce6a47425b6541b84f8ef9546955f4
    userGenerator: authJwt-Yoquito