server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: 'http://localhost:8083'
          predicates:
            - Path=/api/v1/auth/**, /api/v1/roles/**, /api/v1/users/**
        - id: vuelo-service
          uri: 'http://localhost:8084'
          predicates:
            - Path=/api/v1/airlines/**, /api/v1/airports/**, /api/v1/flights/**
eureka:
  client:
    register-with-eureka: false