server:
  port: 8083

spring:
  application:
    name: usuario-service
  jpa:
    properties:
      jdbc:
        time_zone: utc
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/usuario_db
    username: postgres
    password: guerra2350

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka